"""create_new_association table for course, also add image_path field into users

Revision ID: 882bcbff619b
Revises: ceb02ef8b365
Create Date: 2024-09-25 16:53:19.682835

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "882bcbff619b"
down_revision: Union[str, None] = "ceb02ef8b365"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "course_rating_association",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rating", sa.Float(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id"],
            ["courses.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "course_id", "user_id", name="idx_unique_course_user_rating"
        ),
    )
    op.add_column(
        "courses",
        sa.Column(
            "mean_rating", sa.Float(), server_default="0.0", nullable=False
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "image_path",
            sa.String(),
            server_default="/user_images/default.jpg",
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "image_path")
    op.drop_column("courses", "mean_rating")
    op.drop_table("course_rating_association")
    # ### end Alembic commands ###
